### ISSUE TITLE
Add configuration .oclint option to the install. 

### ISSUE THREAD

**Issue by masters3d** [oclint/homebrew-formulae#2]
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#adding-optional-steps

I want to be able to pass it a custom folder where to find the .oclint file. 

I am having trouble specifying this with Travis.

**Comment by ryuichis** [comment]
`.oclint` could be checked in to your repo. It might be a feature that can be added to oclint itself that specifies the path to a custom `.oclint` file.
